
USER_NAME = 'TestUser'
GROUP_TITLE = 'TestGroup'
GROUP_SLUG = 'test-slug'
GROUP_DESCRIPTION = 'Тестовое описание'
POST_TEXT = 'Тестовый текст'

INDEX_URL_NAME = 'posts:index'
GROUP_LIST_URL_NAME = 'posts:group_list'
PROFILE_URL_NAME = 'posts:profile'
POST_CREATE_URL_NAME = 'posts:post_create'
POST_EDIT_URL_NAME = 'posts:post_edit'
POST_DETAIL_URL_NAME = 'posts:post_detail'
USERS_LOGIN_URL_NAME = 'users:login'
COMMENT_ADD_URL_NAME = 'posts:add_comment'
FOLLOW_URL_NAME = 'posts:profile_follow'
UNFOLLOW_URL_NAME = 'posts:profile_unfollow'

INDEX_TEMPLATE = 'posts/index.html'
GROUP_LIST_TEMPLATE = 'posts/group_list.html'
PROFILE_TEMPLATE = 'posts/profile.html'
POST_CREATE_TEMPLATE = 'posts/post_create.html'
POST_EDIT_TEMPLATE = 'posts/post_create.html'
POST_DETAIL_TEMPLATE = 'posts/post_detail.html'
TEMPLATE_404 = 'core/404.html'
