USER_NAME = 'TestUser'

USERS_SINGUP_URL_NAME = 'users:signup'
USERS_LOGOUT_URL_NAME = 'users:logout'
USERS_LOGIN_URL_NAME = 'users:login'
USERS_PWD_CH_URL_NAME = 'users:password_change'
USERS_PWD_CH_D_URL_NAME = 'users:password_change_done'
USERS_PWD_RST_URL_NAME = 'users:password_reset'
USERS_PWD_RST_D_URL_NAME = 'users:password_reset_done'
USERS_PWD_RST_CFRM_URL_NAME = 'users:password_reset_confirm'
USERS_PWD_RST_CMPLT_URL_NAME = 'users:password_reset_complete'


USERS_SINGUP_TEMPLATE = 'users/signup.html'
USERS_LOGOUT_TEMPLATE = 'users/logged_out.html'
USERS_LOGIN_TEMPLATE = 'users/login.html'
USERS_PWD_CH_TEMPLATE = 'users/password_change_form.html'
USERS_PWD_CH_D_TEMPLATE = 'users/password_change_done.html'
USERS_PWD_RST_TEMPLATE = 'users/password_reset_form.html'
USERS_PWD_RST_D_TEMPLATE = 'users/password_reset_done.html'
USERS_PWD_RST_CFRM_TEMPLATE = 'users/password_reset_confirm.html'
USERS_PWD_RST_CMPLT_TEMPLATE = 'users/password_reset_complete.html'
